import Foundation

/// Generates type eraser enum code for protocol types.
///
/// This generator creates enums like AnyProgressViewStyle that wrap
/// concrete style types and conform to SyntaxConvertible for parsing.
public struct TypeEraserGenerator: Sendable {
    
    /// Creates a new type eraser generator.
    public init() {}
    
    /// Generates a type eraser enum for a protocol.
    ///
    /// - Parameters:
    ///   - protocolName: The name of the protocol (e.g., "ProgressViewStyle").
    ///   - eraserName: The name of the eraser enum (e.g., "AnyProgressViewStyle").
    ///   - styleCases: The discovered style cases from protocol extensions.
    /// - Returns: Generated code for the type eraser enum.
    public func generate(
        protocolName: String,
        eraserName: String,
        styleCases: Set<ProtocolStyleParser.StyleCase>
    ) -> GeneratedCode {
        var lines: [String] = []
        
        // Import
        lines.append("import SwiftUI")
        lines.append("import SwiftSyntax")
        lines.append("")
        
        // Header comment
        lines.append("/// Type eraser for \(protocolName).")
        lines.append("///")
        lines.append("/// This enum wraps concrete \(protocolName) implementations")
        lines.append("/// and provides SyntaxConvertible conformance for parsing.")
        lines.append("/// Generated by ModifierSwift.")
        
        // Enum declaration
        lines.append("public enum \(eraserName): Equatable, Sendable {")
        
        // Add cases (sorted for consistency)
        let sortedCases = styleCases.sorted { $0.name < $1.name }
        if sortedCases.isEmpty {
            lines.append("    // No style cases discovered - add manually if needed")
        } else {
            for styleCase in sortedCases {
                lines.append("    case \(styleCase.name)")
            }
        }
        
        lines.append("}")
        lines.append("")
        
        // SyntaxConvertible conformance
        lines.append("extension \(eraserName): SyntaxConvertible {")
        lines.append("    public init?(syntax: some SyntaxProtocol) {")
        
        if sortedCases.isEmpty {
            lines.append("        return nil")
        } else {
            lines.append("        guard let memberAccess = syntax.as(MemberAccessExprSyntax.self) else {")
            lines.append("            return nil")
            lines.append("        }")
            lines.append("        ")
            lines.append("        let memberName = memberAccess.declName.baseName.text")
            lines.append("        ")
            lines.append("        switch memberName {")
            for styleCase in sortedCases {
                lines.append("        case \"\(styleCase.name)\":")
                lines.append("            self = .\(styleCase.name)")
            }
            lines.append("        default:")
            lines.append("            return nil")
            lines.append("        }")
        }
        
        lines.append("    }")
        lines.append("}")
        lines.append("")
        
        // Extension to apply the style (returns the concrete type)
        lines.append("extension \(eraserName) {")
        lines.append("    /// Returns the concrete style value.")
        lines.append("    @ViewBuilder")
        lines.append("    public func apply<Content: View>(to content: Content) -> some View {")
        
        if sortedCases.isEmpty {
            lines.append("        content")
        } else {
            lines.append("        switch self {")
            for styleCase in sortedCases {
                lines.append("        case .\(styleCase.name):")
                lines.append("            content.\(camelToStyleMethod(protocolName))(.\(styleCase.name))")
            }
            lines.append("        }")
        }
        
        lines.append("    }")
        lines.append("}")
        
        let sourceCode = lines.joined(separator: "\n")
        
        return GeneratedCode(
            sourceCode: sourceCode,
            fileName: "\(eraserName).swift",
            modifierCount: sortedCases.count
        )
    }
    
    /// Converts a protocol name to its corresponding modifier method name.
    /// e.g., "ProgressViewStyle" -> "progressViewStyle"
    private func camelToStyleMethod(_ protocolName: String) -> String {
        guard let first = protocolName.first else { return protocolName }
        return first.lowercased() + protocolName.dropFirst()
    }
}
